server:
  http:
    addr: 0.0.0.0:8126
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source:
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 1s
    write_timeout: 1s
